version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: Dockerfile.dev
    container_name: gateway-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - AUTH_SERVER_URL=http://auth-server:3001
      - EVENT_SERVER_URL=http://event-server:3002
      - JWT_SECRET=nexon-2025-assignment!
    volumes:
      - ./gateway-server:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run start:dev
    depends_on:
      - auth-server
      - event-server
    networks:
      - app-network

  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile.dev
    container_name: auth-server
    restart: always
    expose:
      - "3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://root:password@mongodb:27017/auth?authSource=admin
      - JWT_SECRET=nexon-2025-assignment!
      - ADMIN_USER_ID=admin
      - ADMIN_PASSWORD=2025-assignment!
    volumes:
      - ./auth-server:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run start:dev
    depends_on:
      - mongodb
    networks:
      - app-network

  event-server:
    build:
      context: ./event-server
      dockerfile: Dockerfile.dev
    container_name: event-server
    restart: always
    expose:
      - "3002"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:password@mongodb:27017/event?authSource=admin
      - JWT_SECRET=nexon-2025-assignment!
      - PORT=3002
    volumes:
      - ./event-server:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run start:dev
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 